sudo: required

matrix:
  include:
    - language: python
      python: 3.6
      services: mysql
      cache:
        pip: true
      install:
        - pip install django==1.11.1
        - pip install coverage coveralls
        - pip install social-auth-app-django
        - pip install pymysql
      env:
        global:
          - DJANGO_SETTINGS_MODULE="snumeeting_back.travis_settings"
          - PIP_USE_MIRRORS=true
        matrix:
          - DJANGO=1.11.1 DB=mysql
      before_script:
        - cd snumeeting_back
        - mysql -e 'create database travis_ci_db;'
        - python3 manage.py migrate --settings=snumeeting_back.travis_settings
      script:
        - coverage run --branch --source="./snumeeting" manage.py test --settings=snumeeting_back.travis_settings
      after_success:
        - coveralls
      after_script:
        - cd ..

    - language: node_js
      node_js: 8.8
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      cache:
        npm: true
        directories:
          - frontend/node_modules
      before_install:
        - export CHROME_BIN=/usr/bin/google-chrome
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - cd snumeeting-front
        - npm install typings --global
      install:
        - npm install
        - npm install coveralls
        - npm install -g @angular/cli
        - npm install angular2-bootstrap-pagination@2.1.2
      script:
        - ng test --code-coverage --watch false
          #- ng e2e
      after_success:
        - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      after_script:
        - cd ..
