# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 02:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('joinHistory', models.CharField(default='{}', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=64)),
                ('publicity', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ex_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('access_token', models.CharField(max_length=255)),
                ('joinHistory', models.CharField(default='{}', max_length=200)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='snumeeting.College')),
                ('fb_friends', models.ManyToManyField(related_name='_ex_user_fb_friends_+', to='snumeeting.Ex_User')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=64)),
                ('max_member', models.IntegerField()),
                ('is_closed', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings_made', to='snumeeting.Ex_User')),
                ('members', models.ManyToManyField(related_name='meetings_joined', to='snumeeting.Ex_User')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='snumeeting.Interest')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='snumeeting.Subject'),
        ),
        migrations.AddField(
            model_name='ex_user',
            name='subjects',
            field=models.ManyToManyField(related_name='users', to='snumeeting.Subject'),
        ),
        migrations.AddField(
            model_name='ex_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='snumeeting.Ex_User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='snumeeting.Meeting'),
        ),
    ]
