# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snumeeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ex_user',
            name='fb_friends',
            field=models.ManyToManyField(related_name='_ex_user_fb_friends_+', to='snumeeting.Ex_User'),
        ),
        migrations.AddField(
            model_name='ex_user',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
