# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-30 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snumeeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
