# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-29 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snumeeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='joinHistory',
            field=models.CharField(default='{}', max_length=200),
        ),
        migrations.AddField(
            model_name='ex_user',
            name='joinHistory',
            field=models.CharField(default='{}', max_length=200),
        ),
    ]
