# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snumeeting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='users',
        ),
        migrations.AddField(
            model_name='ex_user',
            name='subjects',
            field=models.ManyToManyField(related_name='usersSubjects', to='snumeeting.Subject'),
        ),
        migrations.AlterField(
            model_name='ex_user',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usersCollege', to='snumeeting.College'),
        ),
    ]
