# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snumeeting', '0002_message'),
        ('snumeeting', '0002_meeting_is_closed'),
    ]

    operations = [
    ]
