# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snumeeting', '0002_auto_20171101_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ex_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extendeduser', to=settings.AUTH_USER_MODEL),
        ),
    ]
