# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snumeeting', '0002_auto_20171124_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ex_user',
            name='college',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='usersCollege', to='snumeeting.College'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ex_user',
            name='fb_friends',
            field=models.ManyToManyField(null=True, related_name='_ex_user_fb_friends_+', to='snumeeting.Ex_User'),
        ),
    ]
