# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-30 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snumeeting', '0002_auto_20171129_1449'),
        ('snumeeting', '0002_meeting_is_closed'),
    ]

    operations = [
    ]
