# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snumeeting', '0003_merge_20171130_1338'),
        ('snumeeting', '0003_merge_20171130_1157'),
    ]

    operations = [
    ]
