# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snumeeting', '0003_auto_20171126_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ex_user',
            name='uid',
        ),
    ]
