# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snumeeting', '0005_auto_20171102_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetingsAuthor', to='snumeeting.Ex_User'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='members',
            field=models.ManyToManyField(related_name='meetingsMembers', to='snumeeting.Ex_User'),
        ),
    ]
