# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snumeeting', '0005_auto_20171102_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='ex_user',
            name='name',
            field=models.CharField(default='name', max_length=64),
            preserve_default=False,
        ),
    ]
