# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snumeeting', '0006_auto_20171104_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentsAuthor', to='snumeeting.Ex_User'),
        ),
    ]
