# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snumeeting', '0006_ex_user_name'),
        ('snumeeting', '0007_auto_20171104_1752'),
    ]

    operations = [
    ]
